### ISSUE TITLE
Start using the f* SFW GUI, if already integrated... 

### ISSUE THREAD

**Issue by xparq** [xparq/Out_of_Nothing#206]
I'm being suffocated by the lack of it, still wiring everything to keypresses and watching variables directly...

**Comment by xparq** [comment]
BTW, there's a weird link error (both with DEBUG and wo.) with the same SFW lib that builds fine on its own:

    sfw.lib(Tooltip.obj) : error LNK2019: unresolved external symbol
      "public: __cdecl sf::Text::Text(class sf::Font const &,class sf::String const &,unsigned int)" (??0Text@sf@@QEAA@AEBVFont@1@AEBVString@1@I@Z) 
      referenced in function "public: __cdecl sfw::Text::Text(void)" (??0Text@sfw@@QEAA@XZ)                      
    C:\sz\prj\Out_of_Nothing\tooling\..\out\oon.exe : fatal error LNK1120: 1 unresolved externals

The same SFML lib is used (via the same symlink) by both projects...
